### ISSUE TITLE
Package.json errors

### ISSUE THREAD

**Issue by timbotro** [tbrunain/avalanche-hardhat-fork-tutorial#1]
1. Trailing comma error causes install errors. 
https://github.com/tbrunain/avalanche-hardhat-fork-tutorial/blob/b6c45484f70a2a4f678c05a4fafa8a71ab095b41/package.json#L10

2.  Missing this typechain pkg
   `"typechain": "^5.1.2",`

-----
Perhaps a gotcha for any newbies trying to follow along!

**Comment by Sanghren** [comment]
Good catch, I pushed a fix. Thanks :)
